# Provides a compose file that builds all CVE infrastructure. This is
# meant for use by developers and runs each system in a development mode.
# WARNING: building from this docker compose file may conflict with your
# local docker environment if you've built any individual system's
# application without cleaning your local docker environment.
version: '3'

services:
  # CPS application and database
  db:
    container_name: cvedb
    env_file: ../../cvecps/docker/.docker-env
    image: mysql:5.7
    ports: ["3306:3306"]
  cvecps:
    build:
      context: ../../cvecps/
      dockerfile: docker/Dockerfile.dev
    container_name: cvecps
    depends_on: [db]
    env_file: ../../cvecps/docker/.docker-env
    ports: ["8080:8080"]
    volumes:
      - ../../cvecps/cps:/usr/src/app/cps
      - ../../cvecps/shared:/usr/src/app/shared
      - ../../cvecps/bower_components:/usr/src/app/bower_components
      - ../../cvecps/requirements:/usr/src/app/requirements
  # CVE AWG Services application and database
  docdb:
    image: mongo:3.6.20-xenial
    container_name: mongo
    env_file: ../../cve-services/docker/.docker-env
    ports: ["27017:27017"]
  cveawg:
    container_name: cveawg
    build:
      context: ../../cve-services/
      dockerfile: docker/Dockerfile.dev
    depends_on: [docdb]
    env_file: ../../cve-services/docker/.docker-env
    ports: ["3000:3000"]
    volumes:
      - ../../cve-services/package.json:/app/package.json
      - ../../cve-services/src:/app/src
      - ../../cve-services/test:/app/test
      - ../../cve-services/test-examples:/app/test-examples
      - ../../cve-services/test-utils:/app/test-utils
      - ../../cve-services/.eslintrc.js:/app/.eslintrc.js
  # CVE website running in dev
  cveweb:
    container_name: cveweb
    build:
      context: ../../cve-website/
      dockerfile: docker/Dockerfile
    entrypoint: ["vue-cli-service", "serve", "--port", "8081"]
    ports: ["8081:8081"]
    volumes:
      - ../../cve-website/package.json:/app/package.json
      - ../../cve-website/src:/app/src

