name: "Docker"

# we're running this on pull requests so we can test it
on:
  push:
    branches: [dev, int, release*, workflowTest] # WIP, workflowTest branch is here while testing
  pull_request:
# FIXME: we want this to create a "latest" release on changes
# to `dev` (i.e., whatever dev is at), and actual releases 
# (i.e., branches that start with release) when we create 
# "release" branches ();
# does this do that?
# on:
#   push:
#     branches: ['dev', 'release']

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # we can run tests here, and require that they pass
    # but tests should pass on the pull request used to kick this job off,
    # unless we allow changes to `dev` or `release` branches without PRs
    # needs: npm-run-tests
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build and Push latest to GCR    # always build image with 'latest' tag
      run: |
        docker login docker.pkg.github.com \
          --username ${{ github.actor }} \
          --password ${{ secrets.GITHUB_TOKEN }}
        docker build . \
          --file docker/Dockerfile \
          --tag docker.pkg.github.com/${{github.repository}}/cveawg:latest
        docker push docker.pkg.github.com/${{github.repository}}/cveawg:latest
    - name: Build and Push release to GCR
      if: startsWith(github.ref, 'refs/heads/release')    # only build image with 'release' tag if event comes from a release branch
      run: |
        docker login docker.pkg.github.com \
          --username ${{ github.actor }} \
          --password ${{ secrets.GITHUB_TOKEN }}
        docker build . \
          --file docker/Dockerfile \
          --tag docker.pkg.github.com/${{github.repository}}/cveawg:release
        docker push docker.pkg.github.com/${{github.repository}}/cveawg:release
