name: "Docker"

# we're running this on pull requests so we can test it
on:
  push:
    branches: [dev, int, release*, workflowTest]
  pull_request:
# FIXME: we want this to create a "latest" release on changes
# to `dev` (i.e., whatever dev is at), and actual releases 
# (i.e., branches that start with release and/or are tagged as
# releases) when we create "release" branches ();
# does this do that?
# on:
#   push:
#     branches: ['dev', 'release']

jobs:
  build-and-push-latest-image:
    if: ${{ github.ref != 'refs/heads/release' }}
    runs-on: ubuntu-latest
    # we can run tests here, and require that they pass
    # but tests should pass on the pull request used to kick this job off,
    # unless we allow changes to `dev` or `release` branches without PRs
    # needs: npm-run-tests
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build and Push to GCR
      run: |
        docker login docker.pkg.github.com \
          --username ${{ github.actor }} \
          --password ${{ secrets.GITHUB_TOKEN }}
        docker build . \
          --file docker/Dockerfile \
          --tag docker.pkg.github.com/${{github.repository}}/cveawg:latest
        docker push docker.pkg.github.com/${{github.repository}}/cveawg:latest
  build-and-push-release-image:
    if: ${{ github.ref == 'refs/heads/release' }}
    runs-on: ubuntu-latest
    # we can run tests here, and require that they pass
    # but tests should pass on the pull request used to kick this job off,
    # unless we allow changes to `dev` or `release` branches without PRs
    # needs: npm-run-tests
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build and Push to GCR
      run: |
        docker login docker.pkg.github.com \
          --username ${{ github.actor }} \
          --password ${{ secrets.GITHUB_TOKEN }}
        docker build . \
          --file docker/Dockerfile \
          --tag docker.pkg.github.com/${{github.repository}}/cveawg:release
        docker push docker.pkg.github.com/${{github.repository}}/cveawg:release
